### ISSUE TITLE
Parser doesn't seem to create correct BinOp nodes

### ISSUE THREAD

**Issue by gmalette** [sgnr/Liquider#14]
The AST defines them as having the operator at the end: 

[`BinOpNode = Node.new_type(:binop, :left, :right, :op)`](https://github.com/sgnr/Liquider/blob/f6cdbde7d8bde6aa090c6d50129af19bf3d733ca/lib/liquider/ast.rb#L46)

The [parser tests](https://github.com/sgnr/Liquider/blob/f6cdbde7d8bde6aa090c6d50129af19bf3d733ca/spec/parser_spec.rb#L33-L37) puts it in the "left" property:

```ruby
        Ast::BinOpNode.new(
          :*,
          Ast::StringNode.new('bar'),
          Ast::SymbolNode.new('baz'),
        ),
```

**Comment by sgnr** [comment]
I don't understand. This seems fine to me? `node.binop == :*`?

**Comment by sgnr** [comment]
lol ok I get it. As discussed IRL, do you mid putting `:op` first though?
